name: deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "14.X"
      - name: install yarn
        run: npm install yarn
      - name: install deps
        run: yarn install
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.0.1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASS }}
          port: 22
          source: "dist/"
          target: ${{ secrets.REMOTE_TARGET}}
      
